"""
Export legacy knowledge into docs/legacy_sources.md before deleting old data.
Run ONCE before Batch A/C deletions.
"""
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUTPUT = ROOT / "docs" / "legacy_sources.md"

GOLD_ALPHAS_PATH = ROOT / "gold_alphas.json"
MCP_SKILL_PATH   = ROOT / "mcp_skill.md"
ALPHA_SKILLS_DIR = ROOT / "alpha_skills"


def _load_gold_alphas() -> list:
    if not GOLD_ALPHAS_PATH.exists():
        return []
    with open(GOLD_ALPHAS_PATH, encoding="utf-8") as f:
        return json.load(f)


def _collect_alpha_skill_topics() -> list[str]:
    topics = []
    rawdata = ALPHA_SKILLS_DIR / "rawdata"
    if not rawdata.exists():
        return topics
    for md in sorted(rawdata.rglob("*.md")):
        rel = md.relative_to(rawdata)
        # Use filename as topic name (strip underscores / extension)
        name = md.stem.replace("_", " ").replace("-", " ")
        topics.append(f"- [{name}]({rel.as_posix()})  *(legacy rawdata)*")
    return topics


def build_legacy_doc() -> str:
    lines = [
        "# Legacy Sources — DeerFlow Reading List",
        "",
        "> Auto-generated by `scripts/export_legacy.py`. ",
        "> DeerFlow should read this on first run and mark all entries as `source_type=manual` in SourceRegistry.",
        "",
    ]

    # ── Section 1: Proven Alpha Formulas ─────────────────────────────────────
    alphas = _load_gold_alphas()
    lines += [
        "## 1. Proven Alpha Formulas (Gold Alphas)",
        "",
        "These formulas passed WQB simulation (Sharpe ≥ 1.25, Fitness ≥ 1.0).",
        "Use as reference — do NOT re-submit unchanged. Explore variations instead.",
        "",
    ]
    if alphas:
        for a in alphas:
            sharpe   = a.get("sharpe", "?")
            fitness  = a.get("fitness", "?")
            turnover = round(a.get("turnover", 0) * 100, 1)
            status   = a.get("status", "?")
            name     = a.get("name", "Untitled")
            settings = a.get("settings", "")
            formula  = a.get("formula", "").strip()
            lines += [
                f"### {name}  `[{status}]`",
                f"- Settings: `{settings}` | Sharpe: **{sharpe}** | Fitness: **{fitness}** | TO: {turnover}%",
                "```",
                formula,
                "```",
                "",
            ]
    else:
        lines += ["*(no gold_alphas.json found)*", ""]

    # ── Section 2: Operator & Field Facts from mcp_skill.md ──────────────────
    lines += [
        "## 2. Operator & Field Facts (from mcp_skill.md)",
        "",
    ]
    if MCP_SKILL_PATH.exists():
        content = MCP_SKILL_PATH.read_text(encoding="utf-8")
        lines += [content, ""]
    else:
        lines += ["*(mcp_skill.md not found)*", ""]

    # ── Section 3: Topics from alpha_skills/rawdata/ ─────────────────────────
    lines += [
        "## 3. Research Topics (from alpha_skills/rawdata/)",
        "",
        "These markdown files contained pre-curated alpha research. ",
        "DeerFlow should search for updated versions of these topics online.",
        "",
    ]
    topics = _collect_alpha_skill_topics()
    if topics:
        lines += topics + [""]
    else:
        lines += ["*(alpha_skills/rawdata/ not found or empty)*", ""]

    # ── Section 4: Key Patterns & Hypotheses ─────────────────────────────────
    lines += [
        "## 4. Key Patterns to Explore Further",
        "",
        "Based on gold alpha performance, these signal families showed promise:",
        "",
        "- **Fundamental Correlation Divergence**: `-ts_corr(est_ptp, est_fcf, 20)` family",
        "  - Best performer: Sharpe 1.79, Fitness 1.73 (anl4_afv4_eps_mean vs est_fcf)",
        "  - Hypothesis: when EPS estimates and FCF estimates diverge, stock is mispriced",
        "  - Variations to try: different lookback (15, 30, 60), different field pairs",
        "",
        "- **Earnings Yield Momentum**: `ts_rank(earnings_yield, 60)` family",
        "  - ts_backfill + eps / close → rank in industry",
        "  - Works better in TOP1000 (industry-specific) than TOP3000",
        "",
        "- **Intraday Reversal**: `-(close - open) / open` smoothed",
        "  - High turnover (57%) — needs truncation tuning",
        "",
        "- **EV/CF Zscore**: `-ts_zscore(enterprise_value / cashflow_op, 63)` in industry",
        "  - Classic value signal; solid Sharpe 1.45",
        "",
    ]

    # ── Section 5: Already-Tested Failures (do not retry) ────────────────────
    lines += [
        "## 5. Known Failures / Self-Correlated Alphas",
        "",
        "Do NOT re-test these without significant modification:",
        "",
    ]
    failed = [a for a in alphas if "FAIL" in a.get("status", "") or "CORR" in a.get("status", "")]
    if failed:
        for a in failed:
            lines.append(f"- `{a.get('name', '?')}` — {a.get('status', '?')} | Formula: `{a.get('formula','').strip()[:80]}...`")
        lines.append("")
    else:
        lines += ["*(no recorded failures in gold_alphas.json)*", ""]

    lines += [
        "---",
        "",
        "*This file was auto-generated. The original source files have been archived.*",
        "*Source domain: `wqb_specific`, source type: `manual`*",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    doc = build_legacy_doc()
    OUTPUT.write_text(doc, encoding="utf-8")
    print(f"Written: {OUTPUT}")
    print(f"Size: {len(doc)} chars")
